"""
Export wrist mocap derivatives for alignment with wrist IMU data.

Inputs are generated by export_ascii_fbx_mocap_to_csv.py:
  - mocap_joints_long.csv

Outputs:
  - wrist_mocap_derivatives_long.csv
  - wrist_mocap_derivatives_wide.csv
  - wrist_mocap_derivatives_metadata.json

The CSV contains position, linear velocity, linear acceleration, and angular
velocity estimated from world quaternions. Units follow the FBX position unit.
For this Noitom file the position scale appears to be centimeters, so *_m_* is
also exported assuming 1 FBX unit = 1 cm.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path


DEFAULT_ROOT = Path(r"C:\Users\hand\Desktop\Dataset\0714\002\fbx_mocap_csv")
DEFAULT_JOINTS = DEFAULT_ROOT / "mocap_joints_long.csv"
DEFAULT_OUTDIR = DEFAULT_ROOT
WRISTS = ("LeftHand", "RightHand")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--joints", default=str(DEFAULT_JOINTS))
    parser.add_argument("--outdir", default=str(DEFAULT_OUTDIR))
    parser.add_argument("--unit-scale-to-m", type=float, default=0.01)
    parser.add_argument("--bones", nargs="+", default=list(WRISTS))
    return parser.parse_args()


def q_normalize(q: tuple[float, float, float, float]) -> tuple[float, float, float, float]:
    n = math.sqrt(sum(v * v for v in q))
    if n <= 0:
        return (1.0, 0.0, 0.0, 0.0)
    return tuple(v / n for v in q)  # type: ignore[return-value]


def q_inv(q: tuple[float, float, float, float]) -> tuple[float, float, float, float]:
    w, x, y, z = q_normalize(q)
    return (w, -x, -y, -z)


def q_mul(a: tuple[float, float, float, float], b: tuple[float, float, float, float]) -> tuple[float, float, float, float]:
    aw, ax, ay, az = a
    bw, bx, by, bz = b
    return (
        aw * bw - ax * bx - ay * by - az * bz,
        aw * bx + ax * bw + ay * bz - az * by,
        aw * by - ax * bz + ay * bw + az * bx,
        aw * bz + ax * by - ay * bx + az * bw,
    )


def angular_velocity(q_prev, q_next, dt: float) -> tuple[float, float, float]:
    if dt <= 0:
        return (0.0, 0.0, 0.0)
    dq = q_mul(q_next, q_inv(q_prev))
    dq = q_normalize(dq)
    w, x, y, z = dq
    if w < 0:
        w, x, y, z = -w, -x, -y, -z
    w = max(-1.0, min(1.0, w))
    angle = 2.0 * math.acos(w)
    s = math.sqrt(max(0.0, 1.0 - w * w))
    if s < 1e-9 or angle < 1e-12:
        return (0.0, 0.0, 0.0)
    axis = (x / s, y / s, z / s)
    return (axis[0] * angle / dt, axis[1] * angle / dt, axis[2] * angle / dt)


def norm3(v: tuple[float, float, float]) -> float:
    return math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])


def sub3(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def div3(a, s: float):
    if abs(s) < 1e-12:
        return (0.0, 0.0, 0.0)
    return (a[0] / s, a[1] / s, a[2] / s)


def load_bone_series(path: Path, bones: set[str]) -> dict[str, list[dict]]:
    data = {bone: [] for bone in bones}
    with path.open(newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            bone = row["bone"]
            if bone not in bones:
                continue
            data[bone].append(
                {
                    "frame_index": int(row["frame_index"]),
                    "fbx_tick": int(row["fbx_tick"]),
                    "time_sec": float(row["time_sec"]),
                    "pos": (
                        float(row["world_x"]),
                        float(row["world_y"]),
                        float(row["world_z"]),
                    ),
                    "quat": (
                        float(row["world_qw"]),
                        float(row["world_qx"]),
                        float(row["world_qy"]),
                        float(row["world_qz"]),
                    ),
                    "euler": (
                        float(row["world_rx_deg"]),
                        float(row["world_ry_deg"]),
                        float(row["world_rz_deg"]),
                    ),
                }
            )
    for bone in data:
        data[bone].sort(key=lambda r: r["frame_index"])
    return data


def derivative_rows(bone: str, series: list[dict], scale_to_m: float) -> list[dict]:
    rows = []
    n = len(series)
    for i, current in enumerate(series):
        prev = series[max(0, i - 1)]
        nxt = series[min(n - 1, i + 1)]
        dt = nxt["time_sec"] - prev["time_sec"]
        pos = current["pos"]
        quat = current["quat"]
        vel = div3(sub3(nxt["pos"], prev["pos"]), dt)
        if 0 < i < n - 1:
            dt1 = current["time_sec"] - prev["time_sec"]
            dt2 = nxt["time_sec"] - current["time_sec"]
            v_prev = div3(sub3(current["pos"], prev["pos"]), dt1)
            v_next = div3(sub3(nxt["pos"], current["pos"]), dt2)
            acc = div3(sub3(v_next, v_prev), 0.5 * (dt1 + dt2))
        else:
            acc = (0.0, 0.0, 0.0)
        gyro = angular_velocity(prev["quat"], nxt["quat"], dt)
        row = {
            "frame_index": current["frame_index"],
            "fbx_tick": current["fbx_tick"],
            "time_sec": current["time_sec"],
            "bone": bone,
            "world_x": pos[0],
            "world_y": pos[1],
            "world_z": pos[2],
            "world_qw": quat[0],
            "world_qx": quat[1],
            "world_qy": quat[2],
            "world_qz": quat[3],
            "world_rx_deg": current["euler"][0],
            "world_ry_deg": current["euler"][1],
            "world_rz_deg": current["euler"][2],
            "vel_x_unit_s": vel[0],
            "vel_y_unit_s": vel[1],
            "vel_z_unit_s": vel[2],
            "vel_norm_unit_s": norm3(vel),
            "acc_x_unit_s2": acc[0],
            "acc_y_unit_s2": acc[1],
            "acc_z_unit_s2": acc[2],
            "acc_norm_unit_s2": norm3(acc),
            "gyro_x_rad_s": gyro[0],
            "gyro_y_rad_s": gyro[1],
            "gyro_z_rad_s": gyro[2],
            "gyro_norm_rad_s": norm3(gyro),
            "vel_x_m_s": vel[0] * scale_to_m,
            "vel_y_m_s": vel[1] * scale_to_m,
            "vel_z_m_s": vel[2] * scale_to_m,
            "vel_norm_m_s": norm3(vel) * scale_to_m,
            "acc_x_m_s2": acc[0] * scale_to_m,
            "acc_y_m_s2": acc[1] * scale_to_m,
            "acc_z_m_s2": acc[2] * scale_to_m,
            "acc_norm_m_s2": norm3(acc) * scale_to_m,
        }
        rows.append(row)
    return rows


def fmt_row(row: dict) -> dict:
    out = {}
    for key, value in row.items():
        if isinstance(value, float):
            out[key] = f"{value:.9f}"
        else:
            out[key] = value
    return out


def write_long(path: Path, rows: list[dict]) -> None:
    fields = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(fmt_row(row))


def write_wide(path: Path, rows_by_bone: dict[str, list[dict]]) -> None:
    bones = list(rows_by_bone.keys())
    base = rows_by_bone[bones[0]]
    keys = [
        "world_x",
        "world_y",
        "world_z",
        "world_qw",
        "world_qx",
        "world_qy",
        "world_qz",
        "vel_x_m_s",
        "vel_y_m_s",
        "vel_z_m_s",
        "vel_norm_m_s",
        "acc_x_m_s2",
        "acc_y_m_s2",
        "acc_z_m_s2",
        "acc_norm_m_s2",
        "gyro_x_rad_s",
        "gyro_y_rad_s",
        "gyro_z_rad_s",
        "gyro_norm_rad_s",
    ]
    fields = ["frame_index", "fbx_tick", "time_sec"]
    for bone in bones:
        for key in keys:
            fields.append(f"{bone}_{key}")

    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for i, base_row in enumerate(base):
            row = {
                "frame_index": base_row["frame_index"],
                "fbx_tick": base_row["fbx_tick"],
                "time_sec": base_row["time_sec"],
            }
            for bone in bones:
                source = rows_by_bone[bone][i]
                for key in keys:
                    row[f"{bone}_{key}"] = source[key]
            writer.writerow(fmt_row(row))


def main() -> None:
    args = parse_args()
    joints = Path(args.joints)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    bones = list(args.bones)
    series = load_bone_series(joints, set(bones))
    rows_by_bone = {bone: derivative_rows(bone, series[bone], args.unit_scale_to_m) for bone in bones}
    long_rows = [row for bone in bones for row in rows_by_bone[bone]]

    long_path = outdir / "wrist_mocap_derivatives_long.csv"
    wide_path = outdir / "wrist_mocap_derivatives_wide.csv"
    meta_path = outdir / "wrist_mocap_derivatives_metadata.json"
    write_long(long_path, long_rows)
    write_wide(wide_path, rows_by_bone)

    meta = {
        "source_joints": str(joints),
        "bones": bones,
        "rows_long": len(long_rows),
        "rows_wide": len(rows_by_bone[bones[0]]) if bones else 0,
        "unit_scale_to_m": args.unit_scale_to_m,
        "derivative_method": "central finite difference for velocity/acceleration; quaternion finite difference for angular velocity",
        "recommended_alignment_columns": [
            "gyro_norm_rad_s",
            "gyro_x_rad_s/y/z after estimating axis mapping",
            "acc_norm_m_s2 high-pass or peak timing as secondary cue",
        ],
    }
    meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"long_csv={long_path}")
    print(f"wide_csv={wide_path}")
    print(f"metadata={meta_path}")
    print(f"rows_long={len(long_rows)} rows_wide={meta['rows_wide']}")


if __name__ == "__main__":
    main()
